#!/bin/sh

./plot_avg.py 500/rho2.0 400 > out
./plot_avg.py 500/rho3.3 400 >> out
./plot_avg.py 500/rho4.0 400 >> out
./plot_avg.py 500/rho5.0 400 >> out

./plot_avg.py 1000/rho2.0 650 >> out
./plot_avg.py 1000/rho3.3 450 >> out
./plot_avg.py 1000/rho4.0 400 >> out
./plot_avg.py 1000/rho5.0 670 >> out

./plot_avg.py 1500/rho2.0 800 >> out
./plot_avg.py 1500/rho3.3 400 >> out
./plot_avg.py 1500/rho4.0 450 >> out
./plot_avg.py 1500/rho5.0 600 >> out

./plot_avg.py 2000/rho2.0 600 >> out
./plot_avg.py 2000/rho3.3 550 >> out
./plot_avg.py 2000/rho4.0 600 >> out
./plot_avg.py 2000/rho5.0 500 >> out
